import React from "react";
import { Button } from "./Button";
import "./style.css";

export const Sidebar = () => {
  return (
    <div className="sidebar">
      <Button
        className="jan"
        divClassName="button-instance"
        label="JAN"
        size="medium"
        variant="primary"
      />
      <Button
        className="feb"
        divClassName="design-component-instance-node"
        label="FEB"
        size="medium"
        variant="primary"
      />
      <Button
        className="mar"
        divClassName="mar-2"
        label="MAR"
        size="medium"
        variant="primary"
      />
      <Button
        className="apr"
        divClassName="button-2"
        label="APR"
        size="medium"
        variant="primary"
      />
      <Button
        className="may"
        divClassName="may-2"
        label="MAY"
        size="medium"
        variant="primary"
      />
      <Button
        className="jun"
        divClassName="button-2"
        label="JUN"
        size="medium"
        variant="primary"
      />
      <Button
        className="jul"
        divClassName="jul-2"
        label="JUL"
        size="medium"
        variant="primary"
      />
      <Button
        className="aug"
        divClassName="design-component-instance-node"
        label="AUG"
        size="medium"
        variant="primary"
      />
      <Button
        className="sep"
        divClassName="sep-2"
        label="SEP"
        size="medium"
        variant="primary"
      />
      <Button
        className="oct"
        divClassName="oct-2"
        label="OCT"
        size="medium"
        variant="primary"
      />
      <Button
        className="nov"
        divClassName="nov-2"
        label="NOV"
        size="medium"
        variant="primary"
      />
      <Button
        className="dec"
        divClassName="dec-2"
        label="DEC"
        size="medium"
        variant="primary"
      />
    </div>
  );
};
